# Generated by Django 2.2.1 on 2019-08-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todocore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='fileExtenstion',
            field=models.CharField(default='txt', max_length=50),
            preserve_default=False,
        ),
    ]
