# Generated by Django 2.2.1 on 2019-08-12 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todocore', '0002_file_fileextenstion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='fileExtenstion',
            new_name='fileExtension',
        ),
    ]
