# Generated by Django 2.2.1 on 2019-08-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todocore', '0003_auto_20190812_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='taskGoalEnabled',
            field=models.CharField(default='no', max_length=10),
            preserve_default=False,
        ),
    ]
